import json

from detectron2.engine.hooks import HookBase

from ..config import CfgNode


class WriteMetaHook(HookBase):

    def __init__(self, cfg: CfgNode, model):
        self.output_dir = cfg.OUTPUT_DIR
        self.pretrained = 'No' if cfg.MODEL.WEIGHTS == 0 else f'Yes: {cfg.MODEL.WEIGHTS}'
        self.config_text = cfg.dump()
        self.datasets = ','.join([*cfg.DATASETS.TRAIN, *cfg.DATASETS.TEST])
        self.model_text = repr(model)

    def before_train(self):
        print('Writing metadata')
        metadata = dict(
            path=f'{self.output_dir}/model_final.pth',
            pretrained=self.pretrained,
            trained_on=self.datasets,
            notes=f'<auto generated by {self.__class__.__name__}>'
        )
        with open(f'{self.output_dir}/metadata.json', 'w') as f:
            json.dump(metadata, f, indent=2)

        with open(f'{self.output_dir}/config.yaml', 'w') as f:
            f.write(self.config_text)

        with open(f'{self.output_dir}/model.txt', 'w') as f:
            f.write(self.model_text)
